#!/bin/bash

echo "first set"

cd /data/pately/codes/DPNLP/src/;  python hyperparam_runner_fairgrad.py --is_adv False --adv_start 0.1 --adv_end 3.0 --dataset_name adult -bs 27133 --log_name take_fairgrad_1_bs_27000_linear_seed_256_eps --epochs 2500 --use_lr_schedule False --seed 256 -lr 0.1 --fairness_iterator custom_3 --use_clipping True --use_normalization True --simple_baseline False --fairness_functions demographic_parity_eps --model simple_linear &> log1 &
cd /data/pately/codes/DPNLP/src/;  python hyperparam_runner_fairgrad.py --is_adv False --adv_start 0.1 --adv_end 3.0 --dataset_name adult -bs 27133 --log_name take_fairgrad_2_bs_27000_linear_seed_256_eps --epochs 2500 --use_lr_schedule False --seed 256 -lr 0.1 --fairness_iterator custom_3 --use_clipping True --use_normalization True --simple_baseline False --fairness_functions accuracy_parity_eps --model simple_linear &> log2 &
cd /data/pately/codes/DPNLP/src/;  python hyperparam_runner_fairgrad.py --is_adv False --adv_start 0.1 --adv_end 3.0 --dataset_name adult -bs 27133 --log_name take_fairgrad_3_bs_27000_linear_seed_256_eps --epochs 2500 --use_lr_schedule False --seed 256 -lr 0.1 --fairness_iterator custom_3 --use_clipping True --use_normalization True --simple_baseline False --fairness_functions equal_odds_eps --model simple_linear &> log3 &
cd /data/pately/codes/DPNLP/src/;  python hyperparam_runner_fairgrad.py --is_adv False --adv_start 0.1 --adv_end 3.0 --dataset_name adult -bs 27133 --log_name take_fairgrad_4_bs_27000_linear_seed_256_eps --epochs 2500 --use_lr_schedule False --seed 256 -lr 0.1 --fairness_iterator custom_3 --use_clipping True --use_normalization True --simple_baseline False --fairness_functions equal_opportunity_eps --model simple_linear &> log4 &
cd /data/pately/codes/DPNLP/src/;  python hyperparam_runner_fairgrad.py --is_adv False --adv_start 0.1 --adv_end 3.0 --dataset_name adult -bs 27133 --log_name take_fairgrad_5_bs_27000_linear_seed_256_eps --epochs 2500 --use_lr_schedule False --seed 256 -lr 0.1 --fairness_iterator custom_3 --use_clipping False --use_normalization True --simple_baseline False --fairness_functions demographic_parity_eps --model simple_linear &> log5 &
cd /data/pately/codes/DPNLP/src/;  python hyperparam_runner_fairgrad.py --is_adv False --adv_start 0.1 --adv_end 3.0 --dataset_name adult -bs 27133 --log_name take_fairgrad_6_bs_27000_linear_seed_256_eps --epochs 2500 --use_lr_schedule False --seed 256 -lr 0.1 --fairness_iterator custom_3 --use_clipping False --use_normalization True --simple_baseline False --fairness_functions accuracy_parity_eps --model simple_linear &> log6 &
cd /data/pately/codes/DPNLP/src/;  python hyperparam_runner_fairgrad.py --is_adv False --adv_start 0.1 --adv_end 3.0 --dataset_name adult -bs 27133 --log_name take_fairgrad_7_bs_27000_linear_seed_256_eps --epochs 2500 --use_lr_schedule False --seed 256 -lr 0.1 --fairness_iterator custom_3 --use_clipping False --use_normalization True --simple_baseline False --fairness_functions equal_odds_eps --model simple_linear &> log7 &
cd /data/pately/codes/DPNLP/src/;  python hyperparam_runner_fairgrad.py --is_adv False --adv_start 0.1 --adv_end 3.0 --dataset_name adult -bs 27133 --log_name take_fairgrad_8_bs_27000_linear_seed_256_eps --epochs 2500 --use_lr_schedule False --seed 256 -lr 0.1 --fairness_iterator custom_3 --use_clipping False --use_normalization True --simple_baseline False --fairness_functions equal_opportunity_eps --model simple_linear &> log8 &

wait
echo "second set"

cd /data/pately/codes/DPNLP/src/;  python hyperparam_runner_fairgrad.py --is_adv False --adv_start 0.1 --adv_end 3.0 --dataset_name adult -bs 27133 --log_name take_fairgrad_1_bs_27000_non_linear_seed_256_eps --epochs 2500 --use_lr_schedule False --seed 256 -lr 0.1 --fairness_iterator custom_3 --use_clipping True --use_normalization True --simple_baseline False --fairness_functions demographic_parity_eps --model simple_non_linear &> log9 &
cd /data/pately/codes/DPNLP/src/;  python hyperparam_runner_fairgrad.py --is_adv False --adv_start 0.1 --adv_end 3.0 --dataset_name adult -bs 27133 --log_name take_fairgrad_2_bs_27000_non_linear_seed_256_eps --epochs 2500 --use_lr_schedule False --seed 256 -lr 0.1 --fairness_iterator custom_3 --use_clipping True --use_normalization True --simple_baseline False --fairness_functions accuracy_parity_eps --model simple_non_linear &> log10 &
cd /data/pately/codes/DPNLP/src/;  python hyperparam_runner_fairgrad.py --is_adv False --adv_start 0.1 --adv_end 3.0 --dataset_name adult -bs 27133 --log_name take_fairgrad_3_bs_27000_non_linear_seed_256_eps --epochs 2500 --use_lr_schedule False --seed 256 -lr 0.1 --fairness_iterator custom_3 --use_clipping True --use_normalization True --simple_baseline False --fairness_functions equal_odds_eps --model simple_non_linear &> log11 &
cd /data/pately/codes/DPNLP/src/;  python hyperparam_runner_fairgrad.py --is_adv False --adv_start 0.1 --adv_end 3.0 --dataset_name adult -bs 27133 --log_name take_fairgrad_4_bs_27000_non_linear_seed_256_eps --epochs 2500 --use_lr_schedule False --seed 256 -lr 0.1 --fairness_iterator custom_3 --use_clipping True --use_normalization True --simple_baseline False --fairness_functions equal_opportunity_eps --model simple_non_linear &> log12 &
cd /data/pately/codes/DPNLP/src/;  python hyperparam_runner_fairgrad.py --is_adv False --adv_start 0.1 --adv_end 3.0 --dataset_name adult -bs 27133 --log_name take_fairgrad_5_bs_27000_non_linear_seed_256_eps --epochs 2500 --use_lr_schedule False --seed 256 -lr 0.1 --fairness_iterator custom_3 --use_clipping False --use_normalization True --simple_baseline False --fairness_functions demographic_parity_eps --model simple_non_linear &> log13 &
cd /data/pately/codes/DPNLP/src/;  python hyperparam_runner_fairgrad.py --is_adv False --adv_start 0.1 --adv_end 3.0 --dataset_name adult -bs 27133 --log_name take_fairgrad_6_bs_27000_non_linear_seed_256_eps --epochs 2500 --use_lr_schedule False --seed 256 -lr 0.1 --fairness_iterator custom_3 --use_clipping False --use_normalization True --simple_baseline False --fairness_functions accuracy_parity_eps --model simple_non_linear &> log14 &
cd /data/pately/codes/DPNLP/src/;  python hyperparam_runner_fairgrad.py --is_adv False --adv_start 0.1 --adv_end 3.0 --dataset_name adult -bs 27133 --log_name take_fairgrad_7_bs_27000_non_linear_seed_256_eps --epochs 2500 --use_lr_schedule False --seed 256 -lr 0.1 --fairness_iterator custom_3 --use_clipping False --use_normalization True --simple_baseline False --fairness_functions equal_odds_eps --model simple_non_linear &> log15 &
cd /data/pately/codes/DPNLP/src/;  python hyperparam_runner_fairgrad.py --is_adv False --adv_start 0.1 --adv_end 3.0 --dataset_name adult -bs 27133 --log_name take_fairgrad_8_bs_27000_non_linear_seed_256_eps --epochs 2500 --use_lr_schedule False --seed 256 -lr 0.1 --fairness_iterator custom_3 --use_clipping False --use_normalization True --simple_baseline False --fairness_functions equal_opportunity_eps --model simple_non_linear &> log16 &

wait
echo "third set"

cd /data/pately/codes/DPNLP/src/;  python hyperparam_runner_fairgrad.py --is_adv False --adv_start 0.1 --adv_end 3.0 --dataset_name adult -bs 27133 --log_name take_fairgrad_1_bs_27000_linear_seed_512_eps --epochs 2500 --use_lr_schedule False --seed 512 -lr 0.1 --fairness_iterator custom_3 --use_clipping True --use_normalization True --simple_baseline False --fairness_functions demographic_parity_eps --model simple_linear &> log17 &
cd /data/pately/codes/DPNLP/src/;  python hyperparam_runner_fairgrad.py --is_adv False --adv_start 0.1 --adv_end 3.0 --dataset_name adult -bs 27133 --log_name take_fairgrad_2_bs_27000_linear_seed_512_eps --epochs 2500 --use_lr_schedule False --seed 512 -lr 0.1 --fairness_iterator custom_3 --use_clipping True --use_normalization True --simple_baseline False --fairness_functions accuracy_parity_eps --model simple_linear &> log18 &
cd /data/pately/codes/DPNLP/src/;  python hyperparam_runner_fairgrad.py --is_adv False --adv_start 0.1 --adv_end 3.0 --dataset_name adult -bs 27133 --log_name take_fairgrad_3_bs_27000_linear_seed_512_eps --epochs 2500 --use_lr_schedule False --seed 512 -lr 0.1 --fairness_iterator custom_3 --use_clipping True --use_normalization True --simple_baseline False --fairness_functions equal_odds_eps --model simple_linear &> log19 &
cd /data/pately/codes/DPNLP/src/;  python hyperparam_runner_fairgrad.py --is_adv False --adv_start 0.1 --adv_end 3.0 --dataset_name adult -bs 27133 --log_name take_fairgrad_4_bs_27000_linear_seed_512_eps --epochs 2500 --use_lr_schedule False --seed 512 -lr 0.1 --fairness_iterator custom_3 --use_clipping True --use_normalization True --simple_baseline False --fairness_functions equal_opportunity_eps --model simple_linear &> log20 &
cd /data/pately/codes/DPNLP/src/;  python hyperparam_runner_fairgrad.py --is_adv False --adv_start 0.1 --adv_end 3.0 --dataset_name adult -bs 27133 --log_name take_fairgrad_5_bs_27000_linear_seed_512_eps --epochs 2500 --use_lr_schedule False --seed 512 -lr 0.1 --fairness_iterator custom_3 --use_clipping False --use_normalization True --simple_baseline False --fairness_functions demographic_parity_eps --model simple_linear &> log21 &
cd /data/pately/codes/DPNLP/src/;  python hyperparam_runner_fairgrad.py --is_adv False --adv_start 0.1 --adv_end 3.0 --dataset_name adult -bs 27133 --log_name take_fairgrad_6_bs_27000_linear_seed_512_eps --epochs 2500 --use_lr_schedule False --seed 512 -lr 0.1 --fairness_iterator custom_3 --use_clipping False --use_normalization True --simple_baseline False --fairness_functions accuracy_parity_eps --model simple_linear &> log22 &
cd /data/pately/codes/DPNLP/src/;  python hyperparam_runner_fairgrad.py --is_adv False --adv_start 0.1 --adv_end 3.0 --dataset_name adult -bs 27133 --log_name take_fairgrad_7_bs_27000_linear_seed_512_eps --epochs 2500 --use_lr_schedule False --seed 512 -lr 0.1 --fairness_iterator custom_3 --use_clipping False --use_normalization True --simple_baseline False --fairness_functions equal_odds_eps --model simple_linear &> log23 &
cd /data/pately/codes/DPNLP/src/;  python hyperparam_runner_fairgrad.py --is_adv False --adv_start 0.1 --adv_end 3.0 --dataset_name adult -bs 27133 --log_name take_fairgrad_8_bs_27000_linear_seed_512_eps --epochs 2500 --use_lr_schedule False --seed 512 -lr 0.1 --fairness_iterator custom_3 --use_clipping False --use_normalization True --simple_baseline False --fairness_functions equal_opportunity_eps --model simple_linear &> log24 &

wait
echo "fourth set"

cd /data/pately/codes/DPNLP/src/;  python hyperparam_runner_fairgrad.py --is_adv False --adv_start 0.1 --adv_end 3.0 --dataset_name adult -bs 27133 --log_name take_fairgrad_1_bs_27000_non_linear_seed_512_eps --epochs 2500 --use_lr_schedule False --seed 512 -lr 0.1 --fairness_iterator custom_3 --use_clipping True --use_normalization True --simple_baseline False --fairness_functions demographic_parity_eps --model simple_non_linear &> log25 &
cd /data/pately/codes/DPNLP/src/;  python hyperparam_runner_fairgrad.py --is_adv False --adv_start 0.1 --adv_end 3.0 --dataset_name adult -bs 27133 --log_name take_fairgrad_2_bs_27000_non_linear_seed_512_eps --epochs 2500 --use_lr_schedule False --seed 512 -lr 0.1 --fairness_iterator custom_3 --use_clipping True --use_normalization True --simple_baseline False --fairness_functions accuracy_parity_eps --model simple_non_linear &> log26 &
cd /data/pately/codes/DPNLP/src/;  python hyperparam_runner_fairgrad.py --is_adv False --adv_start 0.1 --adv_end 3.0 --dataset_name adult -bs 27133 --log_name take_fairgrad_3_bs_27000_non_linear_seed_512_eps --epochs 2500 --use_lr_schedule False --seed 512 -lr 0.1 --fairness_iterator custom_3 --use_clipping True --use_normalization True --simple_baseline False --fairness_functions equal_odds_eps --model simple_non_linear &> log27 &
cd /data/pately/codes/DPNLP/src/;  python hyperparam_runner_fairgrad.py --is_adv False --adv_start 0.1 --adv_end 3.0 --dataset_name adult -bs 27133 --log_name take_fairgrad_4_bs_27000_non_linear_seed_512_eps --epochs 2500 --use_lr_schedule False --seed 512 -lr 0.1 --fairness_iterator custom_3 --use_clipping True --use_normalization True --simple_baseline False --fairness_functions equal_opportunity_eps --model simple_non_linear &> log28 &
cd /data/pately/codes/DPNLP/src/;  python hyperparam_runner_fairgrad.py --is_adv False --adv_start 0.1 --adv_end 3.0 --dataset_name adult -bs 27133 --log_name take_fairgrad_5_bs_27000_non_linear_seed_512_eps --epochs 2500 --use_lr_schedule False --seed 512 -lr 0.1 --fairness_iterator custom_3 --use_clipping False --use_normalization True --simple_baseline False --fairness_functions demographic_parity_eps --model simple_non_linear &> log29 &
cd /data/pately/codes/DPNLP/src/;  python hyperparam_runner_fairgrad.py --is_adv False --adv_start 0.1 --adv_end 3.0 --dataset_name adult -bs 27133 --log_name take_fairgrad_6_bs_27000_non_linear_seed_512_eps --epochs 2500 --use_lr_schedule False --seed 512 -lr 0.1 --fairness_iterator custom_3 --use_clipping False --use_normalization True --simple_baseline False --fairness_functions accuracy_parity_eps --model simple_non_linear &> log30 &
cd /data/pately/codes/DPNLP/src/;  python hyperparam_runner_fairgrad.py --is_adv False --adv_start 0.1 --adv_end 3.0 --dataset_name adult -bs 27133 --log_name take_fairgrad_7_bs_27000_non_linear_seed_512_eps --epochs 2500 --use_lr_schedule False --seed 512 -lr 0.1 --fairness_iterator custom_3 --use_clipping False --use_normalization True --simple_baseline False --fairness_functions equal_odds_eps --model simple_non_linear &> log31 &
cd /data/pately/codes/DPNLP/src/;  python hyperparam_runner_fairgrad.py --is_adv False --adv_start 0.1 --adv_end 3.0 --dataset_name adult -bs 27133 --log_name take_fairgrad_8_bs_27000_non_linear_seed_512_eps --epochs 2500 --use_lr_schedule False --seed 512 -lr 0.1 --fairness_iterator custom_3 --use_clipping False --use_normalization True --simple_baseline False --fairness_functions equal_opportunity_eps --model simple_non_linear &> log32 &

wait
echo "fifth set"

cd /data/pately/codes/DPNLP/src/;  python hyperparam_runner_fairgrad.py --is_adv False --adv_start 0.1 --adv_end 3.0 --dataset_name adult -bs 27133 --log_name take_fairgrad_1_bs_27000_linear_seed_1024_eps --epochs 2500 --use_lr_schedule False --seed 1024 -lr 0.1 --fairness_iterator custom_3 --use_clipping True --use_normalization True --simple_baseline False --fairness_functions demographic_parity_eps --model simple_linear &> log33 &
cd /data/pately/codes/DPNLP/src/;  python hyperparam_runner_fairgrad.py --is_adv False --adv_start 0.1 --adv_end 3.0 --dataset_name adult -bs 27133 --log_name take_fairgrad_2_bs_27000_linear_seed_1024_eps --epochs 2500 --use_lr_schedule False --seed 1024 -lr 0.1 --fairness_iterator custom_3 --use_clipping True --use_normalization True --simple_baseline False --fairness_functions accuracy_parity_eps --model simple_linear &> log34 &
cd /data/pately/codes/DPNLP/src/;  python hyperparam_runner_fairgrad.py --is_adv False --adv_start 0.1 --adv_end 3.0 --dataset_name adult -bs 27133 --log_name take_fairgrad_3_bs_27000_linear_seed_1024_eps --epochs 2500 --use_lr_schedule False --seed 1024 -lr 0.1 --fairness_iterator custom_3 --use_clipping True --use_normalization True --simple_baseline False --fairness_functions equal_odds_eps --model simple_linear &> log35 &
cd /data/pately/codes/DPNLP/src/;  python hyperparam_runner_fairgrad.py --is_adv False --adv_start 0.1 --adv_end 3.0 --dataset_name adult -bs 27133 --log_name take_fairgrad_4_bs_27000_linear_seed_1024_eps --epochs 2500 --use_lr_schedule False --seed 1024 -lr 0.1 --fairness_iterator custom_3 --use_clipping True --use_normalization True --simple_baseline False --fairness_functions equal_opportunity_eps --model simple_linear &> log36 &
cd /data/pately/codes/DPNLP/src/;  python hyperparam_runner_fairgrad.py --is_adv False --adv_start 0.1 --adv_end 3.0 --dataset_name adult -bs 27133 --log_name take_fairgrad_5_bs_27000_linear_seed_1024_eps --epochs 2500 --use_lr_schedule False --seed 1024 -lr 0.1 --fairness_iterator custom_3 --use_clipping False --use_normalization True --simple_baseline False --fairness_functions demographic_parity_eps --model simple_linear &> log37 &
cd /data/pately/codes/DPNLP/src/;  python hyperparam_runner_fairgrad.py --is_adv False --adv_start 0.1 --adv_end 3.0 --dataset_name adult -bs 27133 --log_name take_fairgrad_6_bs_27000_linear_seed_1024_eps --epochs 2500 --use_lr_schedule False --seed 1024 -lr 0.1 --fairness_iterator custom_3 --use_clipping False --use_normalization True --simple_baseline False --fairness_functions accuracy_parity_eps --model simple_linear &> log38 &
cd /data/pately/codes/DPNLP/src/;  python hyperparam_runner_fairgrad.py --is_adv False --adv_start 0.1 --adv_end 3.0 --dataset_name adult -bs 27133 --log_name take_fairgrad_7_bs_27000_linear_seed_1024_eps --epochs 2500 --use_lr_schedule False --seed 1024 -lr 0.1 --fairness_iterator custom_3 --use_clipping False --use_normalization True --simple_baseline False --fairness_functions equal_odds_eps --model simple_linear &> log39 &
cd /data/pately/codes/DPNLP/src/;  python hyperparam_runner_fairgrad.py --is_adv False --adv_start 0.1 --adv_end 3.0 --dataset_name adult -bs 27133 --log_name take_fairgrad_8_bs_27000_linear_seed_1024_eps --epochs 2500 --use_lr_schedule False --seed 1024 -lr 0.1 --fairness_iterator custom_3 --use_clipping False --use_normalization True --simple_baseline False --fairness_functions equal_opportunity_eps --model simple_linear &> log40 &

wait
echo "sixth set"

cd /data/pately/codes/DPNLP/src/;  python hyperparam_runner_fairgrad.py --is_adv False --adv_start 0.1 --adv_end 3.0 --dataset_name adult -bs 27133 --log_name take_fairgrad_1_bs_27000_non_linear_seed_1024_eps --epochs 2500 --use_lr_schedule False --seed 1024 -lr 0.1 --fairness_iterator custom_3 --use_clipping True --use_normalization True --simple_baseline False --fairness_functions demographic_parity_eps --model simple_non_linear &> log41 &
cd /data/pately/codes/DPNLP/src/;  python hyperparam_runner_fairgrad.py --is_adv False --adv_start 0.1 --adv_end 3.0 --dataset_name adult -bs 27133 --log_name take_fairgrad_2_bs_27000_non_linear_seed_1024_eps --epochs 2500 --use_lr_schedule False --seed 1024 -lr 0.1 --fairness_iterator custom_3 --use_clipping True --use_normalization True --simple_baseline False --fairness_functions accuracy_parity_eps --model simple_non_linear &> log42 &
cd /data/pately/codes/DPNLP/src/;  python hyperparam_runner_fairgrad.py --is_adv False --adv_start 0.1 --adv_end 3.0 --dataset_name adult -bs 27133 --log_name take_fairgrad_3_bs_27000_non_linear_seed_1024_eps --epochs 2500 --use_lr_schedule False --seed 1024 -lr 0.1 --fairness_iterator custom_3 --use_clipping True --use_normalization True --simple_baseline False --fairness_functions equal_odds_eps --model simple_non_linear &> log43 &
cd /data/pately/codes/DPNLP/src/;  python hyperparam_runner_fairgrad.py --is_adv False --adv_start 0.1 --adv_end 3.0 --dataset_name adult -bs 27133 --log_name take_fairgrad_4_bs_27000_non_linear_seed_1024_eps --epochs 2500 --use_lr_schedule False --seed 1024 -lr 0.1 --fairness_iterator custom_3 --use_clipping True --use_normalization True --simple_baseline False --fairness_functions equal_opportunity_eps --model simple_non_linear &> log44 &
cd /data/pately/codes/DPNLP/src/;  python hyperparam_runner_fairgrad.py --is_adv False --adv_start 0.1 --adv_end 3.0 --dataset_name adult -bs 27133 --log_name take_fairgrad_5_bs_27000_non_linear_seed_1024_eps --epochs 2500 --use_lr_schedule False --seed 1024 -lr 0.1 --fairness_iterator custom_3 --use_clipping False --use_normalization True --simple_baseline False --fairness_functions demographic_parity_eps --model simple_non_linear &> log45 &
cd /data/pately/codes/DPNLP/src/;  python hyperparam_runner_fairgrad.py --is_adv False --adv_start 0.1 --adv_end 3.0 --dataset_name adult -bs 27133 --log_name take_fairgrad_6_bs_27000_non_linear_seed_1024_eps --epochs 2500 --use_lr_schedule False --seed 1024 -lr 0.1 --fairness_iterator custom_3 --use_clipping False --use_normalization True --simple_baseline False --fairness_functions accuracy_parity_eps --model simple_non_linear &> log46 &
cd /data/pately/codes/DPNLP/src/;  python hyperparam_runner_fairgrad.py --is_adv False --adv_start 0.1 --adv_end 3.0 --dataset_name adult -bs 27133 --log_name take_fairgrad_7_bs_27000_non_linear_seed_1024_eps --epochs 2500 --use_lr_schedule False --seed 1024 -lr 0.1 --fairness_iterator custom_3 --use_clipping False --use_normalization True --simple_baseline False --fairness_functions equal_odds_eps --model simple_non_linear &> log47 &
cd /data/pately/codes/DPNLP/src/;  python hyperparam_runner_fairgrad.py --is_adv False --adv_start 0.1 --adv_end 3.0 --dataset_name adult -bs 27133 --log_name take_fairgrad_8_bs_27000_non_linear_seed_1024_eps --epochs 2500 --use_lr_schedule False --seed 1024 -lr 0.1 --fairness_iterator custom_3 --use_clipping False --use_normalization True --simple_baseline False --fairness_functions equal_opportunity_eps --model simple_non_linear &> log48 &


