#!/bin/bash
SEED=$1
echo "linear models on the go adult"
echo "running baseline linear model adult"
cd /data/pately/codes/DPNLP/src/; python hyperparam_runner_fairgrad.py --is_adv False --adv_start 0.1 --adv_end 3.0 --dataset_name adult --log_name take_baseline_linear_seed_$SEED --epochs 1000 --use_lr_schedule False --seed $SEED --fairness_iterator custom_3 --use_clipping True --use_normalization True --simple_baseline True --model simple_linear -lr 0.001 -bs 27133 --optimizer adam &> log1 &
echo "running fair grad linear model with clipping True adult" &
cd /data/pately/codes/DPNLP/src/; python hyperparam_runner_fairgrad.py --is_adv False --adv_start 0.1 --adv_end 3.0 --dataset_name adult -bs 27133 --log_name take_fairgrad_1_bs_27000_linear_seed_$SEED --epochs 2500 --use_lr_schedule False --seed $SEED -lr 0.001 --fairness_iterator custom_3 --use_clipping True --use_normalization True --simple_baseline False  --model simple_linear --optimizer adam --fairness_functions accuracy_parity&> log2 &
cd /data/pately/codes/DPNLP/src/; python hyperparam_runner_fairgrad.py --is_adv False --adv_start 0.1 --adv_end 3.0 --dataset_name adult -bs 27133 --log_name take_fairgrad_2_bs_27000_linear_seed_$SEED --epochs 2500 --use_lr_schedule False --seed $SEED -lr 0.001 --fairness_iterator custom_3 --use_clipping True --use_normalization True --simple_baseline False  --model simple_linear --optimizer adam --fairness_functions demographic_parity&> log3 &
cd /data/pately/codes/DPNLP/src/; python hyperparam_runner_fairgrad.py --is_adv False --adv_start 0.1 --adv_end 3.0 --dataset_name adult -bs 27133 --log_name take_fairgrad_3_bs_27000_linear_seed_$SEED --epochs 2500 --use_lr_schedule False --seed $SEED -lr 0.001 --fairness_iterator custom_3 --use_clipping True --use_normalization True --simple_baseline False  --model simple_linear --optimizer adam --fairness_functions equal_odds&> log4 &
cd /data/pately/codes/DPNLP/src/; python hyperparam_runner_fairgrad.py --is_adv False --adv_start 0.1 --adv_end 3.0 --dataset_name adult -bs 27133 --log_name take_fairgrad_4_bs_27000_linear_seed_$SEED --epochs 2500 --use_lr_schedule False --seed $SEED -lr 0.001 --fairness_iterator custom_3 --use_clipping True --use_normalization True --simple_baseline False  --model simple_linear --optimizer adam --fairness_functions equal_opportunity&> log5 &
echo "running fair grad linear model with clipping False adult" &
cd /data/pately/codes/DPNLP/src/; python hyperparam_runner_fairgrad.py --is_adv False --adv_start 0.1 --adv_end 3.0 --dataset_name adult -bs 27133 --log_name take_fairgrad_5_bs_27000_linear_seed_$SEED --epochs 2500 --use_lr_schedule False --seed $SEED -lr 0.001 --fairness_iterator custom_3 --use_clipping False --use_normalization True --simple_baseline False  --model simple_linear --optimizer adam --fairness_functions accuracy_parity&> log6 &
cd /data/pately/codes/DPNLP/src/; python hyperparam_runner_fairgrad.py --is_adv False --adv_start 0.1 --adv_end 3.0 --dataset_name adult -bs 27133 --log_name take_fairgrad_6_bs_27000_linear_seed_$SEED --epochs 2500 --use_lr_schedule False --seed $SEED -lr 0.001 --fairness_iterator custom_3 --use_clipping False --use_normalization True --simple_baseline False  --model simple_linear --optimizer adam --fairness_functions demographic_parity&> log7 &
cd /data/pately/codes/DPNLP/src/; python hyperparam_runner_fairgrad.py --is_adv False --adv_start 0.1 --adv_end 3.0 --dataset_name adult -bs 27133 --log_name take_fairgrad_7_bs_27000_linear_seed_$SEED --epochs 2500 --use_lr_schedule False --seed $SEED -lr 0.001 --fairness_iterator custom_3 --use_clipping False --use_normalization True --simple_baseline False  --model simple_linear --optimizer adam --fairness_functions equal_odds&> log8 &
cd /data/pately/codes/DPNLP/src/; python hyperparam_runner_fairgrad.py --is_adv False --adv_start 0.1 --adv_end 3.0 --dataset_name adult -bs 27133 --log_name take_fairgrad_8_bs_27000_linear_seed_$SEED --epochs 2500 --use_lr_schedule False --seed $SEED -lr 0.001 --fairness_iterator custom_3 --use_clipping False --use_normalization True --simple_baseline False  --model simple_linear --optimizer adam --fairness_functions equal_opportunity&> log9 &
echo "running baseline non linear model" &
cd /data/pately/codes/DPNLP/src/; python hyperparam_runner_fairgrad.py --is_adv False --adv_start 0.1 --adv_end 3.0 --dataset_name adult --log_name take_baseline_non_linear_seed_$SEED --epochs 1000 --use_lr_schedule False --seed $SEED --fairness_iterator custom_3 --use_clipping True --use_normalization True --simple_baseline True --model simple_non_linear -lr 0.001 -bs 27133 --optimizer adam &> log10 &
echo "running fair grad non linear model with clipping True adult" &
cd /data/pately/codes/DPNLP/src/; python hyperparam_runner_fairgrad.py --is_adv False --adv_start 0.1 --adv_end 3.0 --dataset_name adult -bs 27133 --log_name take_fairgrad_1_bs_27000_non_linear_seed_$SEED --epochs 2500 --use_lr_schedule False --seed $SEED -lr 0.001 --fairness_iterator custom_3 --use_clipping True --use_normalization True --simple_baseline False  --model simple_non_linear --optimizer adam --fairness_functions accuracy_parity&> log11 &
cd /data/pately/codes/DPNLP/src/; python hyperparam_runner_fairgrad.py --is_adv False --adv_start 0.1 --adv_end 3.0 --dataset_name adult -bs 27133 --log_name take_fairgrad_2_bs_27000_non_linear_seed_$SEED --epochs 2500 --use_lr_schedule False --seed $SEED -lr 0.001 --fairness_iterator custom_3 --use_clipping True --use_normalization True --simple_baseline False  --model simple_non_linear --optimizer adam --fairness_functions demographic_parity&> log12 &
cd /data/pately/codes/DPNLP/src/; python hyperparam_runner_fairgrad.py --is_adv False --adv_start 0.1 --adv_end 3.0 --dataset_name adult -bs 27133 --log_name take_fairgrad_3_bs_27000_non_linear_seed_$SEED --epochs 2500 --use_lr_schedule False --seed $SEED -lr 0.001 --fairness_iterator custom_3 --use_clipping True --use_normalization True --simple_baseline False  --model simple_non_linear --optimizer adam --fairness_functions equal_odds&> log13 &
cd /data/pately/codes/DPNLP/src/; python hyperparam_runner_fairgrad.py --is_adv False --adv_start 0.1 --adv_end 3.0 --dataset_name adult -bs 27133 --log_name take_fairgrad_4_bs_27000_non_linear_seed_$SEED --epochs 2500 --use_lr_schedule False --seed $SEED -lr 0.001 --fairness_iterator custom_3 --use_clipping True --use_normalization True --simple_baseline False  --model simple_non_linear --optimizer adam --fairness_functions equal_opportunity&> log14 &
echo "running fair grad non linear model with clipping False adult" &
cd /data/pately/codes/DPNLP/src/; python hyperparam_runner_fairgrad.py --is_adv False --adv_start 0.1 --adv_end 3.0 --dataset_name adult -bs 27133 --log_name take_fairgrad_5_bs_27000_non_linear_seed_$SEED --epochs 2500 --use_lr_schedule False --seed $SEED -lr 0.001 --fairness_iterator custom_3 --use_clipping False --use_normalization True --simple_baseline False  --model simple_non_linear --optimizer adam --fairness_functions accuracy_parity&> log15 &
cd /data/pately/codes/DPNLP/src/; python hyperparam_runner_fairgrad.py --is_adv False --adv_start 0.1 --adv_end 3.0 --dataset_name adult -bs 27133 --log_name take_fairgrad_6_bs_27000_non_linear_seed_$SEED --epochs 2500 --use_lr_schedule False --seed $SEED -lr 0.001 --fairness_iterator custom_3 --use_clipping False --use_normalization True --simple_baseline False  --model simple_non_linear --optimizer adam --fairness_functions demographic_parity&> log16 &
cd /data/pately/codes/DPNLP/src/; python hyperparam_runner_fairgrad.py --is_adv False --adv_start 0.1 --adv_end 3.0 --dataset_name adult -bs 27133 --log_name take_fairgrad_7_bs_27000_non_linear_seed_$SEED --epochs 2500 --use_lr_schedule False --seed $SEED -lr 0.001 --fairness_iterator custom_3 --use_clipping False --use_normalization True --simple_baseline False  --model simple_non_linear --optimizer adam --fairness_functions equal_odds&> log17 &
cd /data/pately/codes/DPNLP/src/; python hyperparam_runner_fairgrad.py --is_adv False --adv_start 0.1 --adv_end 3.0 --dataset_name adult -bs 27133 --log_name take_fairgrad_8_bs_27000_non_linear_seed_$SEED --epochs 2500 --use_lr_schedule False --seed $SEED -lr 0.001 --fairness_iterator custom_3 --use_clipping False --use_normalization True --simple_baseline False  --model simple_non_linear --optimizer adam --fairness_functions equal_opportunity&> log18 &
echo "running adversarial stuff adult" &
cd /data/pately/codes/DPNLP/src/; python hyperparam_runner_fairgrad.py --is_adv True--adv_start 0.1 --adv_end 3.0 --dataset_name adult -bs 1000 --log_name take_adv_non_linear_1_$SEED --epochs 35 --use_lr_schedule False --seed $SEED  --fairness_iterator custom_3 --use_clipping True --use_normalization True --simple_baseline False --fairness_functions accuracy_parity --model simple_non_linear_adv --optimizer adam --lr 0.001 &> log1 &
cd /data/pately/codes/DPNLP/src/; python hyperparam_runner_fairgrad.py --is_adv True --adv_start 0.1 --adv_end 3.0 --dataset_name adult -bs 1000 --log_name take_adv_non_linear_2_$SEED --epochs 35 --use_lr_schedule False --seed $SEED  --fairness_iterator custom_3 --use_clipping True --use_normalization True --simple_baseline False --fairness_functions demographic_parity --model simple_non_linear_adv --optimizer adam --lr 0.001 &> log1 &
cd /data/pately/codes/DPNLP/src/; python hyperparam_runner_fairgrad.py --is_adv True --adv_start 0.1 --adv_end 3.0 --dataset_name adult -bs 1000 --log_name take_adv_non_linear_3_$SEED --epochs 35 --use_lr_schedule False --seed $SEED  --fairness_iterator custom_3 --use_clipping True --use_normalization True --simple_baseline False --fairness_functions equal_odds --model simple_non_linear_adv --optimizer adam --lr 0.001 &> log1 &
cd /data/pately/codes/DPNLP/src/; python hyperparam_runner_fairgrad.py --is_adv True --adv_start 0.1 --adv_end 3.0 --dataset_name adult -bs 1000 --log_name take_adv_non_linear_4_$SEED --epochs 35 --use_lr_schedule False --seed $SEED  --fairness_iterator custom_3 --use_clipping True --use_normalization True --simple_baseline False --fairness_functions equal_opportunity --model simple_non_linear_adv --optimizer adam --lr 0.001 &> log1 &




