echo "linear models on the go encoded_emoji"
echo "running baseline linear model encoded_emoji"
cd /data/pately/codes/DPNLP/src/; python hyperparam_runner_fairgrad.py --is_adv False --adv_start 0.1 --adv_end 3.0 --dataset_name encoded_emoji --log_name take_baseline_linear_seed_256 --epochs 100 --use_lr_schedule False --seed 256 --fairness_iterator custom_3 --use_clipping True --use_normalization True --simple_baseline True --model simple_linear -lr 0.1 -bs 10000 --optimizer sgd &> log1 &
echo "running fair grad linear model with clipping True encoded_emoji" &
cd /data/pately/codes/DPNLP/src/; python hyperparam_runner_fairgrad.py --is_adv False --adv_start 0.1 --adv_end 3.0 --dataset_name encoded_emoji -bs 10000 --log_name take_fairgrad_1_bs_27000_linear_seed_256 --epochs 120 --use_lr_schedule False --seed 256 -lr 0.1 --fairness_iterator custom_3 --use_clipping True --use_normalization True --simple_baseline False  --model simple_linear --optimizer sgd --fairness_functions accuracy_parity &> log3 &
cd /data/pately/codes/DPNLP/src/; python hyperparam_runner_fairgrad.py --is_adv False --adv_start 0.1 --adv_end 3.0 --dataset_name encoded_emoji -bs 10000 --log_name take_fairgrad_2_bs_27000_linear_seed_256 --epochs 120 --use_lr_schedule False --seed 256 -lr 0.1 --fairness_iterator custom_3 --use_clipping True --use_normalization True --simple_baseline False  --model simple_linear --optimizer sgd --fairness_functions demographic_parity &> log4 &
cd /data/pately/codes/DPNLP/src/; python hyperparam_runner_fairgrad.py --is_adv False --adv_start 0.1 --adv_end 3.0 --dataset_name encoded_emoji -bs 10000 --log_name take_fairgrad_3_bs_27000_linear_seed_256 --epochs 120 --use_lr_schedule False --seed 256 -lr 0.1 --fairness_iterator custom_3 --use_clipping True --use_normalization True --simple_baseline False  --model simple_linear --optimizer sgd --fairness_functions equal_odds &> log5 &
cd /data/pately/codes/DPNLP/src/; python hyperparam_runner_fairgrad.py --is_adv False --adv_start 0.1 --adv_end 3.0 --dataset_name encoded_emoji -bs 10000 --log_name take_fairgrad_4_bs_27000_linear_seed_256 --epochs 120 --use_lr_schedule False --seed 256 -lr 0.1 --fairness_iterator custom_3 --use_clipping True --use_normalization True --simple_baseline False  --model simple_linear --optimizer sgd --fairness_functions equal_opportunity &> log6 &
echo "running fair grad linear model with clipping False encoded_emoji" &
cd /data/pately/codes/DPNLP/src/; python hyperparam_runner_fairgrad.py --is_adv False --adv_start 0.1 --adv_end 3.0 --dataset_name encoded_emoji -bs 10000 --log_name take_fairgrad_5_bs_27000_linear_seed_256 --epochs 120 --use_lr_schedule False --seed 256 -lr 0.1 --fairness_iterator custom_3 --use_clipping False --use_normalization True --simple_baseline False  --model simple_linear --optimizer sgd --fairness_functions accuracy_parity &> log7 &
cd /data/pately/codes/DPNLP/src/; python hyperparam_runner_fairgrad.py --is_adv False --adv_start 0.1 --adv_end 3.0 --dataset_name encoded_emoji -bs 10000 --log_name take_fairgrad_6_bs_27000_linear_seed_256 --epochs 120 --use_lr_schedule False --seed 256 -lr 0.1 --fairness_iterator custom_3 --use_clipping False --use_normalization True --simple_baseline False  --model simple_linear --optimizer sgd --fairness_functions demographic_parity &> log8 &
cd /data/pately/codes/DPNLP/src/; python hyperparam_runner_fairgrad.py --is_adv False --adv_start 0.1 --adv_end 3.0 --dataset_name encoded_emoji -bs 10000 --log_name take_fairgrad_7_bs_27000_linear_seed_256 --epochs 120 --use_lr_schedule False --seed 256 -lr 0.1 --fairness_iterator custom_3 --use_clipping False --use_normalization True --simple_baseline False  --model simple_linear --optimizer sgd --fairness_functions equal_odds &> log9 &
cd /data/pately/codes/DPNLP/src/; python hyperparam_runner_fairgrad.py --is_adv False --adv_start 0.1 --adv_end 3.0 --dataset_name encoded_emoji -bs 10000 --log_name take_fairgrad_8_bs_27000_linear_seed_256 --epochs 120 --use_lr_schedule False --seed 256 -lr 0.1 --fairness_iterator custom_3 --use_clipping False --use_normalization True --simple_baseline False  --model simple_linear --optimizer sgd --fairness_functions equal_opportunity &> log10 &
echo "running baseline non linear model" &
cd /data/pately/codes/DPNLP/src/; python hyperparam_runner_fairgrad.py --is_adv False --adv_start 0.1 --adv_end 3.0 --dataset_name encoded_emoji --log_name take_baseline_non_linear_seed_256 --epochs 100 --use_lr_schedule False --seed 256 --fairness_iterator custom_3 --use_clipping True --use_normalization True --simple_baseline True --model simple_non_linear -lr 0.1 -bs 10000 --optimizer sgd &> log11 &
echo "running fair grad non linear model with clipping True encoded_emoji" &
cd /data/pately/codes/DPNLP/src/; python hyperparam_runner_fairgrad.py --is_adv False --adv_start 0.1 --adv_end 3.0 --dataset_name encoded_emoji -bs 10000 --log_name take_fairgrad_1_bs_27000_non_linear_seed_256 --epochs 120 --use_lr_schedule False --seed 256 -lr 0.1 --fairness_iterator custom_3 --use_clipping True --use_normalization True --simple_baseline False  --model simple_non_linear --optimizer sgd --fairness_functions accuracy_parity &> log12 &
cd /data/pately/codes/DPNLP/src/; python hyperparam_runner_fairgrad.py --is_adv False --adv_start 0.1 --adv_end 3.0 --dataset_name encoded_emoji -bs 10000 --log_name take_fairgrad_2_bs_27000_non_linear_seed_256 --epochs 120 --use_lr_schedule False --seed 256 -lr 0.1 --fairness_iterator custom_3 --use_clipping True --use_normalization True --simple_baseline False  --model simple_non_linear --optimizer sgd --fairness_functions demographic_parity &> log13 &
cd /data/pately/codes/DPNLP/src/; python hyperparam_runner_fairgrad.py --is_adv False --adv_start 0.1 --adv_end 3.0 --dataset_name encoded_emoji -bs 10000 --log_name take_fairgrad_3_bs_27000_non_linear_seed_256 --epochs 120 --use_lr_schedule False --seed 256 -lr 0.1 --fairness_iterator custom_3 --use_clipping True --use_normalization True --simple_baseline False  --model simple_non_linear --optimizer sgd --fairness_functions equal_odds &> log14 &
cd /data/pately/codes/DPNLP/src/; python hyperparam_runner_fairgrad.py --is_adv False --adv_start 0.1 --adv_end 3.0 --dataset_name encoded_emoji -bs 10000 --log_name take_fairgrad_4_bs_27000_non_linear_seed_256 --epochs 120 --use_lr_schedule False --seed 256 -lr 0.1 --fairness_iterator custom_3 --use_clipping True --use_normalization True --simple_baseline False  --model simple_non_linear --optimizer sgd --fairness_functions equal_opportunity &> log15 &
echo "running fair grad non linear model with clipping False encoded_emoji" &
cd /data/pately/codes/DPNLP/src/; python hyperparam_runner_fairgrad.py --is_adv False --adv_start 0.1 --adv_end 3.0 --dataset_name encoded_emoji -bs 10000 --log_name take_fairgrad_5_bs_27000_non_linear_seed_256 --epochs 120 --use_lr_schedule False --seed 256 -lr 0.1 --fairness_iterator custom_3 --use_clipping False --use_normalization True --simple_baseline False  --model simple_non_linear --optimizer sgd --fairness_functions accuracy_parity &> log16 &
cd /data/pately/codes/DPNLP/src/; python hyperparam_runner_fairgrad.py --is_adv False --adv_start 0.1 --adv_end 3.0 --dataset_name encoded_emoji -bs 10000 --log_name take_fairgrad_6_bs_27000_non_linear_seed_256 --epochs 120 --use_lr_schedule False --seed 256 -lr 0.1 --fairness_iterator custom_3 --use_clipping False --use_normalization True --simple_baseline False  --model simple_non_linear --optimizer sgd --fairness_functions demographic_parity &> log17 &
cd /data/pately/codes/DPNLP/src/; python hyperparam_runner_fairgrad.py --is_adv False --adv_start 0.1 --adv_end 3.0 --dataset_name encoded_emoji -bs 10000 --log_name take_fairgrad_7_bs_27000_non_linear_seed_256 --epochs 120 --use_lr_schedule False --seed 256 -lr 0.1 --fairness_iterator custom_3 --use_clipping False --use_normalization True --simple_baseline False  --model simple_non_linear --optimizer sgd --fairness_functions equal_odds &> log18 &
cd /data/pately/codes/DPNLP/src/; python hyperparam_runner_fairgrad.py --is_adv False --adv_start 0.1 --adv_end 3.0 --dataset_name encoded_emoji -bs 10000 --log_name take_fairgrad_8_bs_27000_non_linear_seed_256 --epochs 120 --use_lr_schedule False --seed 256 -lr 0.1 --fairness_iterator custom_3 --use_clipping False --use_normalization True --simple_baseline False  --model simple_non_linear --optimizer sgd --fairness_functions equal_opportunity &> log19 &
#echo "running adversarial stuff encoded_emoji" &
#cd /data/pately/codes/DPNLP/src/; python hyperparam_runner_fairgrad.py --is_adv False --adv_start 0.1 --adv_end 3.0 --dataset_name encoded_emoji -bs 1000 --log_name take_adv_non_linear_1_256 --epochs 35 --use_lr_schedule False --seed 256  --fairness_iterator custom_3 --use_clipping True --use_normalization True --simple_baseline False --fairness_functions accuracy_parity --model simple_non_linear_adv --optimizer adam --lr 0.001"
#cd /data/pately/codes/DPNLP/src/; python hyperparam_runner_fairgrad.py --is_adv False --adv_start 0.1 --adv_end 3.0 --dataset_name encoded_emoji -bs 1000 --log_name take_adv_non_linear_2_256 --epochs 35 --use_lr_schedule False --seed 256  --fairness_iterator custom_3 --use_clipping True --use_normalization True --simple_baseline False --fairness_functions demographic_parity --model simple_non_linear_adv --optimizer adam --lr 0.001"
#cd /data/pately/codes/DPNLP/src/; python hyperparam_runner_fairgrad.py --is_adv False --adv_start 0.1 --adv_end 3.0 --dataset_name encoded_emoji -bs 1000 --log_name take_adv_non_linear_3_256 --epochs 35 --use_lr_schedule False --seed 256  --fairness_iterator custom_3 --use_clipping True --use_normalization True --simple_baseline False --fairness_functions equal_odds --model simple_non_linear_adv --optimizer adam --lr 0.001"
#cd /data/pately/codes/DPNLP/src/; python hyperparam_runner_fairgrad.py --is_adv False --adv_start 0.1 --adv_end 3.0 --dataset_name encoded_emoji -bs 1000 --log_name take_adv_non_linear_4_256 --epochs 35 --use_lr_schedule False --seed 256  --fairness_iterator custom_3 --use_clipping True --use_normalization True --simple_baseline False --fairness_functions equal_opportunity --model simple_non_linear_adv --optimizer adam --lr 0.001"




